// 请求地址

import { backend_proxy_string, backend_api, ws_server_http_proxy_string } from "./ConstVars";


// 后端接口
export const urls = {
    headimageURL: backend_api+"/files/headimage/",
    backimageURL: backend_api+"/files/backimage/",
    artworkimageURL: backend_api+"/files/gallery/",
    artworkimagePreviewURL: backend_api+"/files/GalleryPreview/",
    checkLogin: backend_proxy_string+'/core/checkLogin',
    getSessionId: backend_proxy_string+'/core/getSessionId',
    getUser: backend_proxy_string+'/core/getUser',
    getSessionUser: backend_proxy_string+'/core/getSessionUser',
    login: backend_proxy_string+'/core/login',
    logout: backend_proxy_string+'/core/logout',
    uploadArtwork: backend_proxy_string+'/core/uploadArtwork',
    getArtworks: backend_proxy_string+'/core/getArtworks',
    getTags: backend_proxy_string+'/core/getTags',
    getRegisterCode: backend_proxy_string+'/core/getRegisterCode',
    register: backend_proxy_string+'/core/register',
    getResetPasswordCode: backend_proxy_string+'/core/getResetPasswordCode',
    resetPassword: backend_proxy_string+'/core/resetPassword',
    addBoardMessage: backend_proxy_string+'/core/addBoardMessage',
    getBoradMessages: backend_proxy_string+'/core/getBoradMessages',
    getDBRecordCount: backend_proxy_string+'/core/getDBRecordCount',
    getArtwork: backend_proxy_string+'/core/getArtwork',
    editUser: backend_proxy_string+'/core/editUser',
    editUserImage: backend_proxy_string+'/core/editUserImage',
    getEditUserImportantCode: backend_proxy_string+'/core/getEditUserImportantCode',
    editUserImportant: backend_proxy_string+'/core/editUserImportant',
    clearUserImage: backend_proxy_string+'/core/clearUserImage',
    getTagsArtwork: backend_proxy_string+'/core/getTagsArtwork',
    sendCommentArtwork: backend_proxy_string+'/core/sendCommentArtwork',
    getArtworkComments: backend_proxy_string+'/core/getArtworkComments',
    getCommentGalleryCount: backend_proxy_string+'/core/getCommentGalleryCount',
    pawArtworkMedia: backend_proxy_string+'/core/pawArtworkMedia',
    starArtworkMedia: backend_proxy_string+'/core/starArtworkMedia',
    getArtworkPawAreaInfo: backend_proxy_string+'/core/getArtworkPawAreaInfo',
    haveWatch: backend_proxy_string+'/core/haveWatch',
    watchUser: backend_proxy_string+'/core/watchUser',
    getUserInfoCount: backend_proxy_string+'/core/getUserInfoCount',
    getUserWatch: backend_proxy_string+'/core/getUserWatch',
    getStarArtworks: backend_proxy_string+'/core/getStarArtworks',
    getUserStarInfoCount: backend_proxy_string+'/core/getUserStarInfoCount',
    editArtwork: backend_proxy_string+'/core/editArtwork',
    deleteArtwork: backend_proxy_string+'/core/deleteArtwork',
    getUserNoticePawArtwork: backend_proxy_string+'/core/getUserNoticePawArtwork',
    getUserNoticeTextEcho: backend_proxy_string+'/core/getUserNoticeTextEcho',
    getUserNoticeWatcher: backend_proxy_string+'/core/getUserNoticeWatcher',
    noticeFinishRead: backend_proxy_string+'/core/noticeFinishRead',
    noticeNotRead: backend_proxy_string+'/core/noticeNotRead',
    getNoticenum: backend_proxy_string+'/core/getNoticenum',
    getUserTrendUsers: backend_proxy_string+'/core/getUserTrendUsers',
    trendFinishRead: backend_proxy_string+'/core/trendFinishRead',
    trendNotRead: backend_proxy_string+'/core/trendNotRead',
    getTrendnum: backend_proxy_string+'/core/getTrendnum',
    getUserTrendArtworks: backend_proxy_string+'/core/getUserTrendArtworks',
    searchTags: backend_proxy_string+'/core/searchTags',
    editTag: backend_proxy_string+'/core/editTag',
    deleteTag: backend_proxy_string+'/core/deleteTag',
    getTopTags: backend_proxy_string+'/core/getTopTags',
    searchPinkCandy: backend_proxy_string+'/core/searchPinkCandy',
    getRegisterableUsername: backend_proxy_string+'/core/getRegisterableUsername',
}

// socket服务器的http服务接口
export const socket_http_urls = {
    createRoom: ws_server_http_proxy_string+'/core/createRoom',
    getRoom: ws_server_http_proxy_string+'/core/getRoom',
    joinRoom: ws_server_http_proxy_string+'/core/joinRoom',
    haveJoin: ws_server_http_proxy_string+'/core/haveJoin',
    getMessages: ws_server_http_proxy_string+'/core/getMessages',
    getRoomMembers: ws_server_http_proxy_string+'/core/getRoomMembers',
    getRooms: ws_server_http_proxy_string+'/core/getRooms',
    editRoom: ws_server_http_proxy_string+'/core/editRoom',
    deleteRoom: ws_server_http_proxy_string+'/core/deleteRoom',
    searchRooms: ws_server_http_proxy_string+'/core/searchRooms',
    getMyRooms: ws_server_http_proxy_string+'/core/getMyRooms',
    getOnlineMembers: ws_server_http_proxy_string+'/core/getOnlineMembers',
    inviteRoomMember: ws_server_http_proxy_string+'/core/inviteRoomMember',
    removeRoomMember: ws_server_http_proxy_string+'/core/removeRoomMember',
}
